### ISSUE TITLE
Display percentage level of the air pollution

### ISSUE THREAD

**Issue by rjaros87** [rjaros87/pm-station-usb#10]
I think it good be to see percentage level of the air pollution beside the measurements.

**Comment by sanchin** [comment]
Added in b8e9ae944ba4a5d3a66beec293379a696a4c7589

**Comment by rjaros87** [comment]
and the Desktop version? :)

**Comment by pskowronek** [comment]
here you are

**Comment by pskowronek** [comment]
impl similar to Android one (configurable "safe" levels)
