### ISSUE TITLE
[Desktop-Win10] checked "show in system tray" causes app to hang on all multiple monitors under win10

### ISSUE THREAD

**Issue by dareknowak** [rjaros87/pm-station-usb#15]
Noticed some issue with desktop app, release 1.1.0 and native virtual desktop capability under windows 10

env:
windows 10 enterprise

steps to reproduce:
1. open app
2. mark the "show in system tray"
3. restart app
4. system tray app icon is visible
5. switch to some other virtual desktop under windows 10, 
(x) application is still there, visible on all virtual desktops,
(/) should be visible only under one virtual desktop 

regards
D.

**Comment by pskowronek** [comment]
pls close if the fix works for you

**Comment by dareknowak** [comment]
Superb.
