### ISSUE TITLE
[Desktop-Win10] [multiple virtual desktops] window size not saved after app restart

### ISSUE THREAD

**Issue by dareknowak** [rjaros87/pm-station-usb#16]
Seems like there is some issue with saving the windows size under windows 10 and when some additional monitors are added in extended mode

env.
windows 10
pm-home-station released 1.1.0 version

steps:
1. open app
2. drag it to additional virtual desktop (extended display)
3. change window size
4. restart app
(x)windows size has not been saved

steps when it works:
1. open app
2. drag it to main desktop window (main monitor)
3. change window size
4. restart app
(/)windows size is saved

Remark:
set the window size on "main" desktop and drag it to the extended desktop, close it there **it will not remember its size** :)

**Comment by pskowronek** [comment]
pls close if the fix works for you

**Comment by dareknowak** [comment]
superb!
