### ISSUE TITLE
[D] Build version in the footer of desktop app

### ISSUE THREAD

**Issue by dareknowak** [rjaros87/pm-station-usb#19]
When possible please add build version in the footer of Desktop application.
Near //pm-home-station element?

**Comment by pskowronek** [comment]
Actively refusing :) - trying to avoid clutter in the app window.
pls state at least 2 or 3 desktop apps that expose the version in such a way.
Instead I would add "new released version" available feature.

**Comment by dareknowak** [comment]
Sure. The examples for Windows 10 are:

Foobar2000
E-deklaracje
Lightworks Pro

all installed at my lenovo 

:)

**Comment by pskowronek** [comment]
Let's ignore E-deklaracje :)
Might consider version in the titlebar akin to foobar2000.
