### ISSUE TITLE
[D] brushed amelinium does not fill the resized window

### ISSUE THREAD

**Issue by dareknowak** [rjaros87/pm-station-usb#20]
Img attached.

To reproduce:

1. Open windows desktop version
2. Resize window
3. Background does not fill resized window

![capture](https://user-images.githubusercontent.com/14890662/37246069-a87c412a-24a2-11e8-8287-39ea55369ceb.PNG)

**Comment by pskowronek** [comment]
> Background does not fill resized window

The background image is definite so... it must end somewhere and ... because Sun/Oracle was unable to fix Frame#setMaximumSize and its cooperation with Layout Manager for like 20yrs you can see that effect on Windows and probably on Linux. Just don't resize too much or use OSX :P

**Comment by dareknowak** [comment]
works like a charm and looks!
