### ISSUE TITLE
[Desktop] Headless mode for desktop app

### ISSUE THREAD

**Issue by pskowronek** [rjaros87/pm-station-usb#22]
Allow for headless mode in desktop app (i.e. command line mode)

**Comment by pskowronek** [comment]
Added the following command:
 -c,--headless   headless mode (cli mode) - autostarts measurements based on config

To log into csv file add the following entries to config file:
csv.log.file = /path/to/file.csv
csv.log.enabled = true

The above command starts to measure until either sensor disconnected or app killed (or interrupted).

**Comment by rjaros87** [comment]
Add above knowledge in README.md ;)

**Comment by pskowronek** [comment]
- Moved some bits from README.md to WIKI 
- Added info about headless mode on the following wiki page: https://github.com/rjaros87/pm-home-station/wiki/Features
