### ISSUE TITLE
[Android&Desktop]Nova PM SDS011

### ISSUE THREAD

**Issue by gabrielcramer** [rjaros87/pm-station-usb#28]
First of all, great job for this project.

I think it would be great to have support for Nova PM SDS011

**Comment by pskowronek** [comment]
We don't currently plan to add this device as it doesn't bring any new features. We're now considering PMS5003ST (#29) as it can provide temp, humidity & formaldehyde readings.

**Comment by rjaros87** [comment]
@0merta you can always contribute :)
