### ISSUE TITLE
New PMS5003ST

### ISSUE THREAD

**Issue by rjaros87** [rjaros87/pm-station-usb#29]
Maybe we should consider to test new device? @pskowronek @sanchin  @idf3d 
PMS5003**ST** provide additionally measurements of:
- Formaldehyde
- Temperature
- Humidity

Device: https://pl.aliexpress.com/item/4000036196650.html 
(Optional) Adapter https://pl.aliexpress.com/item/33040162499.html

**Comment by pskowronek** [comment]
+1

**Comment by pskowronek** [comment]
Manual in english:
https://www.thaieasyelec.com/downloads/ESEN298/PMS5003ST_Datasheet.pdf

**Comment by pskowronek** [comment]
merged to master
