### ISSUE TITLE
[Desktop] Newer version notification, rebuild app

### ISSUE THREAD

**Issue by dareknowak** [rjaros87/pm-station-usb#9]
Is it possible to check the git history and pop up some notification within the java app that application could be rebuild in order to get latest commits?

**Comment by pskowronek** [comment]
Technically it is possible, however not sure if it is reasonable. Would be better to implement this feature to check the versions of released app(s) only. For self-built apps I would suggest to add the project to your github account Watch list (https://help.github.com/articles/about-notifications/) or execute git pull from time to time :)

**Comment by pskowronek** [comment]
Maybe not exactly what you wanted but new released version checking has been added here: 67ad1a8cb07faebfd162a95b8cac24013c5aacda

Closing.
